version: '3'
services:
  db:
    image: "postgres:latest"
    container_name: demo_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
  minio:
    image: minio/minio:RELEASE.2022-05-04T07-45-27Z
    container_name: demo_minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - ./.data/minio:/data